PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE temps(
	name DEFAULT 'RPi.rgb',
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	r NUMERIC DEFAULT 0,
	g NUMERIC DEFAULT 0,
	b NUMERIC DEFAULT 0
);

COMMIT;
